### ISSUE TITLE
Continuous Integration for automation of source to package

### ISSUE THREAD

**Issue by nkhedekar** [JdeRobot/assets#23]
It would be nice to have an online continuous integration system for this repository. 

Could the maintainers please detail the manual process being followed at the moment and share any suggestions for this enhancement?

**Comment by nkhedekar** [comment]
@jmplaza, @diegomrt can you please let me know the current process and files used for manual integration?

**Comment by nkhedekar** [comment]
@fqez could you please help out with this?

**Comment by fqez** [comment]
Hi @nkhedekar. Sorry for the late reply, haven't checked this repo in a while :( 

There is no continuous integration system for this repository at the moment because it is meant for "static" files such as model and word files for gazebo, images and such.  Nonetheless there is a mechanism for building a debian package out of the gazebo directory (only) which we build for every release of JdeRobot. What do you want to achieve exactly?

Regards.

**Comment by jmplaza** [comment]
The idea is to automatically generate the debian package from each pull request merged in this repository (or most of the process). This way "apt-get install jderobot-assets" would install the most updated release.

**Comment by fqez** [comment]
Okey, I get the idea. We then need an automated process for publishing our debian packages, which we do not have right now. I will try to make the package release automatic for this repo then.

**Comment by nkhedekar** [comment]
Excellent! The issue was mostly to say that I would like to help with that :)

**Comment by nkhedekar** [comment]
@fqez Could you please also detail the process you are using for packaging this repository as a similar process is required for the drones repository too.

**Comment by fqez** [comment]
Hi @nkhedekar. The packaging for this repository is not yet implemented. It does only work for assets directory, and the package generation consist on building the assets directory and creating a debian package using CMake. We do it this way because this method was inherited by the base repository where all this assets come from. 
You could try and reproduce a CMakeLists.txt file for the drones directory, so you can generate packages with only 3 commands 

```
cmake . && make && cpack .
```

or try to refactor the whole package generation to generate all packages from this repo at once with those 3 commands.

What do you think?

**Comment by nkhedekar** [comment]
Hi @fqez , I was actually thinking of having something more on the lines of releasing with Bloom (into the official build farm) the procedure of which is provided in a [this tutorial](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease). The rationale for this is that as we plan to switch to ROS, it makes sense for the packages to be added and released through the official build farm.

**Comment by fqez** [comment]
Seems good to me. What do you think about this one @jmplaza?

**Comment by nkhedekar** [comment]
For the purpose of releasing to ROS, I have started the branch `kinetic-devel`. I have currently added the assets of 3 exercises into it. These have been tested to be working. I would like to stress that it is imperative that we ensure that the models do not have any ICE dependencies and minimal custom dependencies. 

The release of both the repositories - assets and drones would require release repositories (at present this means the creation of two repositories with just a readme with the titles : `assets-release` and `drones-release`). These can be within the same organization or within a separate organization solely for the purpose of release repositories (as has been done by https://github.com/ros-gbp). 

@jmplaza could you please create the repositories (either in this org or in a separate org) as specified here(point 3 on http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease) and add me to them?

**Comment by nkhedekar** [comment]
Just to keep everyone updated, the pull request for adding assets and drones to the official rosdistro has been merged. There is no news on the date of the next sync on discourse, but as soon as its done, the packages shall be available from the official sources!

**Comment by nkhedekar** [comment]
The discussion for the upcoming sync can be tracked [here](https://discourse.ros.org/t/preparing-for-kinetic-sync-2019-07-22/10015/6)

**Comment by fqez** [comment]
Hi @nkhedekar I've just seen our assets package in the new release of ROS kinetic, awesome job indeed :)
I've been told by @jmplaza that we will be migrating all our assets to the kinetic-devel branch to make it the new master branch in the near future. For now, I will try to learn the process to make a new release using Bloom as you suggested some posts above with the ColorTuner tool (https://github.com/JdeRobot/ColorTuner.git). 
Do I need to know something else about ROS build farm besides the official documentation you linked? and are we planning to move all this to ROS Melodic? Since we just upgraded our supported Ubuntu distro from Xenial to Bionic some weeks ago.

Again, really good job and keep it up!

**Comment by nkhedekar** [comment]
Thank you @fqez ! 

Yep, so we should test (and ensure rosification of) all assets before moving them to the the kinetic-devel branch which will be the new master branch in the near future. In the distant future since we shall be moving to melodic, we can have another branch titled melodic-devel that is used to release the package into melodic. 

Apart from assets, I have run into an issue with the rqt_drone_teleop and drone_wrapper both of which were also released at the same time. I think there might actually be a little information required that is beyond the current documentation (atleast what pertains to the aforementioned packages and hence to color_tuner too). I would recommend going through the best practices documentation on the ros wiki (http://wiki.ros.org/BestPractices) and by legged robotics (https://github.com/leggedrobotics/ros_best_practices/wiki). One point that would be of immediate concern would be to change the name from ColorTuner to color_tuner as mentioned here: http://wiki.ros.org/ROS/Patterns/Conventions

**Comment by nkhedekar** [comment]
As the continuous integration for this has been established using the official ROS build farm, I am closing this issue. The status and build flags have also been added to the documentation. 

Upcoming: 
Documentation on how to add releasable assets
